global_defs {
    router_id HAPROXY_A
    enable_script_security
    script_user root
}

vrrp_script check_haproxy {
    script "/usr/local/bin/check-haproxy.sh"
    interval 2
    timeout 2
    fall 2
    rise 2
}

vrrp_sync_group MULTITENANT_GROUP {
    group {
        PUBLIC_VIPS
        TENANT_A_GATEWAY
        TENANT_B_GATEWAY
    }
}

vrrp_instance PUBLIC_VIPS {
    state BACKUP
    interface ens38
    virtual_router_id 30
    priority 150
    advert_int 1

    unicast_src_ip 2001:db8:20:0::2
    unicast_peer {
        2001:db8:20:0::3
    }

    virtual_ipaddress {
        2001:db8:20:10::a/64 dev ens33
        2001:db8:20:10::b/64 dev ens33
    }

    track_script {
        check_haproxy
    }
}

vrrp_instance TENANT_A_GATEWAY {
    state BACKUP
    interface ens38
    virtual_router_id 10
    priority 150
    advert_int 1

    unicast_src_ip 2001:db8:20:0::2
    unicast_peer {
        2001:db8:20:0::3
    }

    virtual_ipaddress {
        2001:db8:2a:20::a/64 dev ens36.10
    }

    track_script {
        check_haproxy
    }
}

vrrp_instance TENANT_B_GATEWAY {
    state BACKUP
    interface ens38
    virtual_router_id 20
    priority 150
    advert_int 1

    unicast_src_ip 2001:db8:20:0::2
    unicast_peer {
        2001:db8:20:0::3
    }

    virtual_ipaddress {
        2001:db8:2b:20::a/64 dev ens36.20
    }

    track_script {
        check_haproxy
    }
}
